Repository very-indecisive-studios/tracktgt-website, pull requests merged in 2022-06, with the labels that each got.

#20 [FEATURE] Books tracking UI
  app/components/home/HomeNavbar.tsx
  app/components/home/books/TrackBookEditorModal.tsx
  app/routes/home/books/$id.tsx
  app/routes/home/books/index.tsx
  app/routes/home/games/index.tsx
  app/routes/home/index.tsx
Labels: feature

#25 [BUG] Fix show type bug
  app/components/home/shows/TrackShowEditorModal.tsx
  app/routes/home/shows/$id.tsx
  app/routes/home/shows/index.tsx
  app/routes/home/shows/search.tsx
  backend/backendAPIClient.ts
Labels: bug

#26 [BUG][ENHANCE] Improve verification flow
  app/routes/account/verify/index.tsx
  app/utils/session.server.tsx
Labels: bug, enhancement

#27 [ENHANCE] Setup end-to-end testing
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
  tests/account/login.spec.ts
  tests/account/logout.spec.ts
  tests/global-setup.ts
  tests/home.spec.ts
  tests/home/books/id.spec.ts
  tests/home/books/index.spec.ts
  tests/home/books/search.spec.ts
  tests/home/games/id.spec.ts
  tests/home/games/index.spec.ts
  tests/home/games/search.spec.ts
  tests/home/index.spec.ts
  tests/home/shows/id.spec.ts
  tests/home/shows/index.spec.ts
  tests/home/shows/search.spec.ts
  tests/home/user.spec.ts
  tests/index.spec.ts
Labels: enhancement
